# workflow to show how to develop workflows in branches
name: Develop in a branch

on: [pull_request, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: echo "PR title is '${{ github.event.pull_request.title }}'."
      - run: |
          echo "Workflow triggered in branch '${{ github.ref }}'."
          echo "Workflow triggered by event '${{ github.event_name }}'."
          echo "Workflow triggered by actor '${{ github.actor }}''."
      - run: |
          echo "::debug::This is a debug message."
          echo "::warning::This is a warning message."
          echo "::error::This is an error message."          
      - uses: actions/checkout@v4.1.0
      - uses: devops-actions/actionlint@v0.1.2
